server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/volldb
    username: postgres
    password: postgres
    configuration:
      maximum-pool-size: 30
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # Flyway
  flyway:
    locations: classpath:db/migration, classpath:db/data
  servlet:
    multipart:
      max-file-size: 2MB