version: '3.5'

services:
  voll-db:
    container_name: postgres-voll-db
    image: postgres:13.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: volldb
    ports:
      - "5431:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
volumes:
  postgresvolldb: